{% set python_min = "3.10" %}
{% set name = "txl-jpterm" %}
{% set version = "0.3.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/txl_jpterm-{{ version }}.tar.gz
  sha256: 9bf36155bc45acb5c535ce1b214b1528314783b54c5ba026b9fc0e5ddf0d995a

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - hatchling
  run:
    - python >={{ python_min }}
    - txl =0.3.2

test:
  requires:
    - pip
    - python {{ python_min }}
  commands:
    - pip check
  imports:
    - txl_jpterm

about:
  home: https://github.com/davidbrochart/jpterm/blob/main/plugins/jpterm
  summary: TXL plugin for the jpterm app
  dev_url: https://github.com/davidbrochart/jpterm/blob/main/plugins/jpterm
  license_file: LICENSE.txt
  license: MIT
  license_family: MIT

extra:
  recipe-maintainers:
    - davidbrochart
