{% set name = "txl-jpterm" %}
{% set version = "0.2.14" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/txl_jpterm-{{ version }}.tar.gz
  sha256: ed5800b7d88f93eb2e1a28a23ffa0fced297c2963d5bc9ba7a459e64d820797e

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv

requirements:
  host:
    - python >=3.10
    - pip
    - hatchling
  run:
    - python >=3.10
    - txl >=0.2.18,<0.3.0

test:
  # `pip check` was disabled, see: https://github.com/conda-forge/staged-recipes/pull/26869
  #
  # requires:
  #   - pip
  # commands:
  #   - pip check
  imports:
    - txl_jpterm

about:
  home: https://github.com/davidbrochart/jpterm/blob/main/plugins/jpterm
  summary: TXL plugin for the jpterm app
  dev_url: https://github.com/davidbrochart/jpterm/blob/main/plugins/jpterm
  license_file: LICENSE.txt
  license: MIT
  license_family: MIT

extra:
  recipe-maintainers:
    - davidbrochart
