{% set name = "txl-jpterm" %}
{% set version = "0.2.15" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/txl_jpterm-{{ version }}.tar.gz
  sha256: efcd0bfc5306c89f18e75b5b144863822dd739f81efb126554d81dc7124e4a22

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv

requirements:
  host:
    - python >=3.10
    - pip
    - hatchling
  run:
    - python >=3.10
    - txl >=0.2.18,<0.3.0

test:
  # `pip check` was disabled, see: https://github.com/conda-forge/staged-recipes/pull/26869
  #
  # requires:
  #   - pip
  # commands:
  #   - pip check
  imports:
    - txl_jpterm

about:
  home: https://github.com/davidbrochart/jpterm/blob/main/plugins/jpterm
  summary: TXL plugin for the jpterm app
  dev_url: https://github.com/davidbrochart/jpterm/blob/main/plugins/jpterm
  license_file: LICENSE.txt
  license: MIT
  license_family: MIT

extra:
  recipe-maintainers:
    - davidbrochart
